### ISSUE TITLE
Not compatible with Pixel Tablet

### ISSUE THREAD

**Issue by PacoBell** [seii/tiltkart#15]
**Describe the bug**
Attempting to even install the APK on a Pixel Tablet results in the following error:

```
App not installed as app isn't compatible with your tablet.
```

**To Reproduce**
1. Download APK from GitHub
2. Tap on it in file manager
3. See error

**Expected behavior**
Being able to install the app on this Pixel Tablet

**Screenshots**
![Screenshot_20231021-212048~2.png](https://github.com/seii/tiltkart/assets/42870/8e6c64c2-a697-4b8f-a8de-a6bc6e87f0d0)

**Desktop (please complete the following information):**
 - OS:
    - [ ] PC
    - [✔️] Android
 - Program Version
 - Using TiltFive?
    - [✔️] Yes
    - [ ] No
 - Input Method:
    - [ ] Keyboard
    - [ ] Gamepad
    - [✔️] Android touchscreen
    - [✔️] TiltFive wand

**Additional context**
I'm running Graphene OS on this tablet, but I don't think that's really an issue because another T5 kart demo from another dev works just fine on this same device.

**Comment by seii** [comment]
Pasting follow-up message from the same user, obtained via the Tilt Five Discord ([here](https://discord.com/channels/559819554335752192/1086406347601494108/1165492570458177667)):
> Just tried the Tilt Kart demo on my Pixel Tablet. When directly connected, glasses and Wand pair in the T5 app just fine, but only audio works and the projectors never kick in. I'm guessing not enough power available from the port? So I plugged the tablet into my TB4 powered dock and the glasses into the dock and it ran the demo great with sound and video. Are there diagnostic logs available that'll tell me if it's a power issue?

The Tilt Five glasses do, indeed, need a certain level of power. Tilt Five has lamented that, apparently, USB 3 ports vary widely between devices and manufacturers on how they will actually handle power draw. Testing any suspected power issue with a powered hub (as this user did) is one of the best available troubleshooting steps currently.

Tilt Five also does allow the generation of diagnostic logs within their own driver software, although I'm uncertain how helpful they would be as that is outside the scope of my game. As of the time of this comment, to see instructions on how to generate T5 logs, you can go to Tilt Five's [Troubleshooting](https://www.tiltfive.com/support/troubleshooting) webpage, scroll down, and click "How to record logs in the Tilt Five Control Panel".

Resolving issue, thank you for the report!
